services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend:9092
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 200:200
    depends_on:
      - backend
    networks:
      - psabot-net

  backend:
    build:
      context: flask
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9092
    volumes:
      - ./flask:/src
    depends_on:
      -  mongo
    networks:
      - psabot-net

  mongo:
    image: mongo
    networks:
      - psabot-net

networks:
  psabot-net:
    external: true
