name: mpabot_data_controller

services:
  datacontroller-web:
    container_name: datacontroller-web
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=datacontroller-backend:9092
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 200:200
    depends_on:
      - datacontroller-backend
    networks:
      - subnet

  datacontroller-backend:
    container_name: datacontroller-backend
    image: datacontroller_backend
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9092
      - MONGO_URI=mongodb://datacontroller-mongo:27017/datacontroller_db
    volumes:
      - ./app:/src
    depends_on:
      -  datacontroller-mongo
    networks:
      - data-net
      - subnet

  datacontroller-mongo:
    container_name: datacontroller-mongo
    image: mongo
    ports:
      - 50001:27017
    volumes:
      - datacontroller-data:/data/db
    networks:
      - subnet


networks:
  data-net:
    driver: bridge
  subnet:
    driver: bridge


volumes:
  datacontroller-data: